/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TeamRouteImport } from './routes/team'
import { Route as DeveloperApiKeysRouteImport } from './routes/developer.api-keys'
import { Route as DeveloperWebhooksRouteImport } from './routes/developer.webhooks'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings.workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperApiKeysRoute = DeveloperApiKeysRouteImport.update({
  id: '/developer/api-keys',
  path: '/developer/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperWebhooksRoute = DeveloperWebhooksRouteImport.update({
  id: '/developer/webhooks',
  path: '/developer/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => InboxRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/settings/workspace',
  path: '/settings/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/channels': typeof ChannelsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/team': typeof TeamRoute
  '/developer/api-keys': typeof DeveloperApiKeysRoute
  '/developer/webhooks': typeof DeveloperWebhooksRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/channels': typeof ChannelsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/team': typeof TeamRoute
  '/developer/api-keys': typeof DeveloperApiKeysRoute
  '/developer/webhooks': typeof DeveloperWebhooksRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/channels': typeof ChannelsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/team': typeof TeamRoute
  '/developer/api-keys': typeof DeveloperApiKeysRoute
  '/developer/webhooks': typeof DeveloperWebhooksRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/channels'
    | '/inbox'
    | '/knowledge'
    | '/profile'
    | '/team'
    | '/developer/api-keys'
    | '/developer/webhooks'
    | '/inbox/$conversationId'
    | '/settings/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/channels'
    | '/inbox'
    | '/knowledge'
    | '/profile'
    | '/team'
    | '/developer/api-keys'
    | '/developer/webhooks'
    | '/inbox/$conversationId'
    | '/settings/workspace'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/channels'
    | '/inbox'
    | '/knowledge'
    | '/profile'
    | '/team'
    | '/developer/api-keys'
    | '/developer/webhooks'
    | '/inbox/$conversationId'
    | '/settings/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ChannelsRoute: typeof ChannelsRoute
  InboxRoute: typeof InboxRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  ProfileRoute: typeof ProfileRoute
  TeamRoute: typeof TeamRoute
  DeveloperApiKeysRoute: typeof DeveloperApiKeysRoute
  DeveloperWebhooksRoute: typeof DeveloperWebhooksRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/api-keys': {
      id: '/developer/api-keys'
      path: '/developer/api-keys'
      fullPath: '/developer/api-keys'
      preLoaderRoute: typeof DeveloperApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/webhooks': {
      id: '/developer/webhooks'
      path: '/developer/webhooks'
      fullPath: '/developer/webhooks'
      preLoaderRoute: typeof DeveloperWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxConversationIdRoute: typeof InboxConversationIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxConversationIdRoute: InboxConversationIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ChannelsRoute: ChannelsRoute,
  InboxRoute: InboxRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  ProfileRoute: ProfileRoute,
  TeamRoute: TeamRoute,
  DeveloperApiKeysRoute: DeveloperApiKeysRoute,
  DeveloperWebhooksRoute: DeveloperWebhooksRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
